[general]
bars = 6
framerate = 60
sensitivity = 100
[input]
method = pulse
source = alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 100
