# ##################
# ### SYSTEM SERVICES ###
# ##################
exec-once = awww-daemon &
exec-once = hyprpolkitagent
exec-once = playerctld daemon
# Monitor brightness and hardware controls
exec-once = systemctl --user start hyprpolkitagent
exec-once = bash /home/agony/.local/Astrea/Settings/components/visual/scripts/monitor_apply.sh
# Screen vibrancy
exec-once = nvibrant 0 950