# ##################
# ### SYSTEM SERVICES ###
# ##################

# Monitor brightness and hardware controls
exec-once = bash -c 'for code in 70 6E 6C; do ddcutil setvcp $code 45; done'

# Screen vibrancy
exec = nvibrant 0 950