# ################
# ### LAYOUT ###
# ################

dwindle {
    pseudotile     = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 1
    disable_hyprland_logo   = false    # no splash at startup
    enable_swallow          = true    # terminal swallowing
    swallow_regex           = ^(kitty|Alacritty)$
    focus_on_activate       = false   # don't steal focus on urgent hint
}

