# ##################
# ### VISUAL EFFECTS ###
# ##################
decoration {
    rounding       = 14
    rounding_power = 2

    active_opacity   = 1.0
    inactive_opacity = 0.90

    shadow {
        enabled        = true
        range          = 40
        render_power   = 4
        offset         = 0, 10
        color          = rgba(00000060)
        color_inactive = rgba(00000028)
    }

    blur {
        enabled           = true
        size              = 10
        passes            = 2
        noise             = 0.015
        contrast          = 0.90
        brightness        = 0.80
        vibrancy          = 0.3
        vibrancy_darkness = 0.6
        new_optimizations = true
        xray              = false
        special           = true
        popups            = true
    }
}