# ######################
# ### VISUAL EFFECTS ###
# ######################

decoration {
    rounding       = 14
    rounding_power = 2

    active_opacity   = 1.0
    inactive_opacity = 0.92

    dim_inactive = true
    dim_strength = 0.08  # subtle depth cue — clearly active vs inactive
    dim_special = 0

    shadow {
        enabled        = true
        range          = 50
        render_power   = 3
        offset         = 0, 8
        color          = rgba(00000055)
        color_inactive = rgba(00000020)
    }

    blur {
        enabled           = true
        size              = 3     # smaller radius → fewer samples
        passes            = 3     # more passes compensate → same quality, better perf
        noise             = 0.012
        contrast          = 0.87
        brightness        = 1
        vibrancy          = 0.25
        vibrancy_darkness = 0
        new_optimizations = true
        xray              = false
        special           = true
        popups            = true
        popups_ignorealpha = 0.2
    }
}

#  LIQUID GLASS, WAITING A LAYER IMPLEMENTATION!
plugin:hyprglass {
    enabled        = 0
    default_theme  = dark
    default_preset = default

    blur_strength = 2
    blur_iterations = 2

    refraction_strength = 0.8
    chromatic_aberration = 1

    specular_strength = 0
    glass_opacity = 2

    edge_thickness = 0.1

    lens_distortion = 0
    
    brightness = 1
    contrast = 1.15

}

plugin:dynamic-cursors {
    enabled = false
    mode = none


    shake {
        enabled   = true
        nearest   = false
        threshold = 6.0
        base      = 4.0
        speed     = 4.0
        influence = 0.0
        limit     = 0.0
        timeout   = 2000
        effects   = false
        ipc       = false
    }

    hyprcursor {
        nearest    = false
        enabled    = true
        resoluton = 96
        fallback   = clientside
    }
}