general {
    border_size = 1
    # A mágica das 8 cores (sentido horário):
    # Topo-Esq, Topo, Topo-Dir, Direita, Baixo-Dir, Baixo, Baixo-Esq, Esquerda
    
    col.active_border = rgba(ffffff33) rgba(ffffff00) rgba(ffffff00) rgba(ffffff33) 45deg

    col.inactive_border = rgba(00000000)
}