# ################
# ### GENERAL ###
# ################

general {
    gaps_in  = 4
    gaps_out = 10
    border_size = 1

    layout       = dwindle
    allow_tearing = false
    resize_on_border = true  # resize window by dragging any edge, not just corners
}
