# ##################
# ### UI COMPONENTS ###
# ##################

exec-once = swaync
# Status bar (Waybar)
exec-once = pkill -x playerctl || true
exec-once = quickshell -p ~/.config/quickshell

# GTK Themes and Dark Mode
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark" # para aplicativos GTK4 
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark" # para aplicativos GTK3 
