# ############################
# ### AUTOSTART — MASTER ###
# ############################

# System-level services
source = ~/.config/hypr/conf/startup/system/services.conf
exec-once = hyprpolkitagent
# Interface components
source = ~/.config/hypr/conf/startup/interface/ui.conf
source = ~/.config/hypr/conf/startup/system/wallpaper.conf

# GTK3
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
# GTK4
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"