# ##############################
# ### WINDOWS AND WORKSPACES ###
# ##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/
# See https://wiki.hypr.land/Configuring/Workspace-Rules/

# ── Layer Rules ───────────────────────────────────────────────────
layerrule = blur on,           match:namespace bar
layerrule = ignore_alpha 0.5,  match:namespace bar
layerrule = blur on,           match:namespace spotlight
layerrule = ignore_alpha 0.5,  match:namespace spotlight
layerrule = blur on,          match:namespace topbar-popup
layerrule = ignore_alpha 0.5, match:namespace topbar-popup
layerrule = blur on,          match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
# ── Window Rules ──────────────────────────────────────────────────

windowrule {
    # Ignore maximize requests from all apps
    name          = suppress-maximize-events
    match:class   = .*
    suppress_event = maximize
}

windowrule {
    # Fix XWayland drag issues
    name             = fix-xwayland-drags
    match:class      = ^$
    match:title      = ^$
    match:xwayland   = true
    match:float      = true
    match:fullscreen = false
    match:pin        = false
    no_focus         = true
}

windowrule {
    name        = hyprland-run-position
    match:class = hyprland-run
    move        = 20 monitor_h-120
    float       = yes
}

windowrule {
    name        = loupe-float
    match:class = org.gnome.Loupe
    float       = yes
    center      = yes
}

windowrule {
    name        = ark-float
    match:class = org.kde.ark
    float       = yes
    center      = yes
}
windowrule {
    name        = zen-pip
    match:class = ^(zen)$
    match:title = ^(Picture-in-Picture)$
    float       = yes
    center      = yes
}

windowrule[zen-login] {
    match:class = ^(zen)$
    match:title = ^(Fazer login)$
    float       = true
}

windowrule {
    name        = zen-login
    match:class = zen
    match:title = ^(Bitwarden)$
    float       = yes
    center      = yes
    size        = 450 625
}

windowrule {
    name        = steam-settings
    match:class = steam
    match:title = ^(Steam — Configurações)$
    float       = yes
    center      = yes
}

windowrule {
    name        = KDE-Filedialog
    match:class = org.freedesktop.impl.portal.desktop.kde
    float       = yes
    center      = no
    size        = 1100 600
}