# ##################
# ### SYSTEM SERVICES ###
# ##################

exec-once = hyprpolkitagent
exec-once = playerctld daemon
# Monitor brightness and hardware controls
exec-once = systemctl --user start hyprpolkitagent
exec-once = bash /etc/Astrea-Settings/scripts/monitor_apply.sh
