# ##################
# ### SYSTEM SERVICES ###
# ##################

exec-once = hyprpolkitagent
exec-once = playerctld daemon
# Monitor brightness and hardware controls
exec-once = systemctl --user start hyprpolkitagent
exec-once = bash -c 'for code in 70 6E 6C; do ddcutil setvcp $code 45; done'

# Screen vibrancy
exec = nvibrant 0 950