# ─────────────────────────────────────────────────────────────────────────────
# Hyprland Configuration — Root Entry Point
# https://wiki.hypr.land/Configuring/
# ─────────────────────────────────────────────────────────────────────────────

# Hardware
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/environment.conf

# source = ~/.config/hypr/conf/optimizations/nvidia.conf
# source = ~/.config/hypr/conf/optimizations/amd.conf
# source = ~/.config/hypr/conf/optimizations/intel.conf

# Applications & Keybindings
source = ~/.config/hypr/conf/programs.conf
source = ~/.config/hypr/conf/keybindings.conf

# Autostart
source = ~/.config/hypr/conf/autostart.conf

# UI & Theme
source = ~/.config/hypr/conf/theme.conf

# Input
source = ~/.config/hypr/conf/input.conf

# Rules
source = ~/.config/hypr/conf/windowrules.conf