monitor=DP-1
monitor_id=0
resolution=1920x1080
refreshrate=165
bitdepth=10
scale=1
vrr=2
saturation=95
night_shift=0
night_shift_strength=25
night_shift_schedule=1
night_shift_start=21:30
night_shift_end=08:00