# ##################
# ### AUTOSTART MASTER ###
# ##################

# System config
source = ~/.config/hypr/conf/autostart_config/system/services.conf

# Interface config
source = ~/.config/hypr/conf/autostart_config/interface/ui.conf
source = ~/.config/hypr/conf/autostart_config/interface/wallpaper.conf

# You can add more categories here as needed:
# source = ~/.config/hypr/conf/autostart_config/apps/user_apps.conf
