# ##################
# ### THEME MASTER ###
# ##################

# General layout behavior
general {
    layout = dwindle
    allow_tearing = false
    resize_on_border = false
    gaps_out = 8 8 8 8  # top right bottom left
}

# Source theme modules
source = ~/.config/hypr/conf/ui_config/colors/borders.conf
source = ~/.config/hypr/conf/ui_config/fx/decoration.conf
source = ~/.config/hypr/conf/ui_config/animations/default.conf

# Layout settings
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = false
}
