# ##############################
# ### WINDOWS AND WORKSPACES ###
# ##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = XDG_MENU_PREFIX,arch-

layerrule = blur on, match:namespace bar
layerrule = ignore_alpha 0.5, match:namespace bar

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.5, match:namespace rofi

windowrule {
    name = google-oauth-popup
    match:title = .*accounts\.google\.com.*
    float = yes
    center = yes
    size = 500 650
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
windowrule {
name = loupe-float
    match:class = org.gnome.Loupe
float = yes
center = yes
}

windowrule {
name = ark-float
    match:class = org.kde.ark
float = yes
center = yes
}