# =============================================================
# update-manifest.conf — Astrea-OS
# Formato: ORIGEM_NO_REPO    DESTINO_NO_SISTEMA    [PERMISSAO]
# =============================================================

# ─── App principal (/opt) ────────────────────────────────────
opt/Astrea/                             /opt/Astrea/                                755

# ─── Configs do sistema ──────────────────────────────────────
etc/os-release                          /etc/os-release                             644

# ─── Configs do usuário (~/.config) ─────────────────────────
.config/hypr/                           /home/agony/.config/hypr/                   644
.config/quickshell/                     /home/agony/.config/quickshell/             644
.config/kitty/                          /home/agony/.config/kitty/                  644
.config/cava/                           /home/agony/.config/cava/                   644
.config/fastfetch/                      /home/agony/.config/fastfetch/              644
.config/rofi/                           /home/agony/.config/rofi/                   644
.config/swaync/                         /home/agony/.config/swaync/                 644
.config/MangoHud/                       /home/agony/.config/MangoHud/               644

# ─── Dados locais (~/.local/share) ───────────────────────────
.local/share/Astrea/                    /home/agony/.local/share/Astrea/            644

# ─── Tema SDDM ───────────────────────────────────────────────
system/sddm/themes/Borealis/            /usr/share/sddm/themes/Borealis/            644

# ─── Serviço systemd (monitor) ───────────────────────────────
system/services/Astrea-Settings/monitor_apply.sh    /usr/local/bin/monitor_apply.sh     755

# ─── Scripts executáveis ─────────────────────────────────────
.local/share/Astrea/Settings/components/visual/scripts/get-monitor-info.py  /home/agony/.local/share/Astrea/Settings/components/visual/scripts/get-monitor-info.py  755
.local/share/Astrea/Settings/components/visual/scripts/monitor_apply.sh     /home/agony/.local/share/Astrea/Settings/components/visual/scripts/monitor_apply.sh     755